// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bootstrap is the predicate function for bootstrap builders.
type Bootstrap func(*sql.Selector)

// Version is the predicate function for version builders.
type Version func(*sql.Selector)
