// Code generated by go-enum DO NOT EDIT.
// Version: 0.3.10
// Revision: 07a5b318d9ef317345f0cfca0c9347eda0e2bfc4
// Build Date: 2022-01-23T20:31:33Z
// Built By: goreleaser

package of

var SupportModuleNames = []Name{
	NameAccount,
	NameAdmin,
	NameCenter,
	NameNode,
	NameBootNode,
	NameUpgrade,
	NameMedia,
	NameKernel,
	NameGateway,
}

const (
	// NameNotSet is a Name of type when you don't specify a name
	NameNotSet Name = "notset"
	// NameAccount is a Name of type Account.
	NameAccount Name = "account"
	// NameAdmin is a Name of type Admin.
	NameAdmin Name = "admin"
	// NameCenter is a Name of type Center.
	NameCenter Name = "center"
	// NameNode is a Name of type Node.
	NameNode Name = "node"
	// NameBootNode is a Name of type BootNode.
	NameBootNode Name = "bootnode"
	// NameUpgrade is a Name of type Upgrade.
	NameUpgrade Name = "upgrade"
	// NameMedia is a Name of type Media.
	NameMedia Name = "media"
	// NameKernel is a Name of type Kernel.
	NameKernel Name = "kernel"
	// NameGateway is a Name of type Gateway.
	NameGateway Name = "gateway"
)
