// Code generated by entc, DO NOT EDIT.

package media

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tikafog/of/dbc/media/informationv1"
	"github.com/tikafog/of/dbc/media/predicate"
)

// InformationV1Delete is the builder for deleting a InformationV1 entity.
type InformationV1Delete struct {
	config
	hooks    []Hook
	mutation *InformationV1Mutation
}

// Where appends a list predicates to the InformationV1Delete builder.
func (iv *InformationV1Delete) Where(ps ...predicate.InformationV1) *InformationV1Delete {
	iv.mutation.Where(ps...)
	return iv
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (iv *InformationV1Delete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(iv.hooks) == 0 {
		affected, err = iv.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InformationV1Mutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			iv.mutation = mutation
			affected, err = iv.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(iv.hooks) - 1; i >= 0; i-- {
			if iv.hooks[i] == nil {
				return 0, fmt.Errorf("media: uninitialized hook (forgotten import media/runtime?)")
			}
			mut = iv.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, iv.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (iv *InformationV1Delete) ExecX(ctx context.Context) int {
	n, err := iv.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (iv *InformationV1Delete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: informationv1.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: informationv1.FieldID,
			},
		},
	}
	if ps := iv.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, iv.driver, _spec)
}

// InformationV1DeleteOne is the builder for deleting a single InformationV1 entity.
type InformationV1DeleteOne struct {
	iv *InformationV1Delete
}

// Exec executes the deletion query.
func (ivo *InformationV1DeleteOne) Exec(ctx context.Context) error {
	n, err := ivo.iv.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{informationv1.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ivo *InformationV1DeleteOne) ExecX(ctx context.Context) {
	ivo.iv.ExecX(ctx)
}
