// Code generated by entc, DO NOT EDIT.

package instruct

const (
	// Label holds the string label denoting the instruct type in the database.
	Label = "instruct"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCurrentUnix holds the string denoting the current_unix field in the database.
	FieldCurrentUnix = "current_unix"
	// FieldUpdatedUnix holds the string denoting the updated_unix field in the database.
	FieldUpdatedUnix = "updated_unix"
	// Table holds the table name of the instruct in the database.
	Table = "instructs"
)

// Columns holds all SQL columns for instruct fields.
var Columns = []string{
	FieldID,
	FieldCurrentUnix,
	FieldUpdatedUnix,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCurrentUnix holds the default value on creation for the "current_unix" field.
	DefaultCurrentUnix int64
	// DefaultUpdatedUnix holds the default value on creation for the "updated_unix" field.
	DefaultUpdatedUnix int64
)
