// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Instruct is the predicate function for instruct builders.
type Instruct func(*sql.Selector)

// Pin is the predicate function for pin builders.
type Pin func(*sql.Selector)

// Version is the predicate function for version builders.
type Version func(*sql.Selector)
