// Code generated by ent, DO NOT EDIT.

package upgrade

import (
	"github.com/google/uuid"
	"github.com/tikafog/of/dbc/upgrade/schema"
	"github.com/tikafog/of/dbc/upgrade/update"
	"github.com/tikafog/of/dbc/upgrade/version"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	updateMixin := schema.Update{}.Mixin()
	updateMixinFields0 := updateMixin[0].Fields()
	_ = updateMixinFields0
	updateMixinFields1 := updateMixin[1].Fields()
	_ = updateMixinFields1
	updateFields := schema.Update{}.Fields()
	_ = updateFields
	// updateDescCreatedUnix is the schema descriptor for created_unix field.
	updateDescCreatedUnix := updateMixinFields1[0].Descriptor()
	// update.DefaultCreatedUnix holds the default value on creation for the created_unix field.
	update.DefaultCreatedUnix = updateDescCreatedUnix.Default.(int64)
	// updateDescUpdatedUnix is the schema descriptor for updated_unix field.
	updateDescUpdatedUnix := updateMixinFields1[1].Descriptor()
	// update.DefaultUpdatedUnix holds the default value on creation for the updated_unix field.
	update.DefaultUpdatedUnix = updateDescUpdatedUnix.Default.(int64)
	// updateDescOs is the schema descriptor for os field.
	updateDescOs := updateFields[0].Descriptor()
	// update.DefaultOs holds the default value on creation for the os field.
	update.DefaultOs = updateDescOs.Default.(string)
	// updateDescArch is the schema descriptor for arch field.
	updateDescArch := updateFields[1].Descriptor()
	// update.DefaultArch holds the default value on creation for the arch field.
	update.DefaultArch = updateDescArch.Default.(string)
	// updateDescVersion is the schema descriptor for version field.
	updateDescVersion := updateFields[2].Descriptor()
	// update.DefaultVersion holds the default value on creation for the version field.
	update.DefaultVersion = updateDescVersion.Default.(string)
	// updateDescRid is the schema descriptor for rid field.
	updateDescRid := updateFields[3].Descriptor()
	// update.DefaultRid holds the default value on creation for the rid field.
	update.DefaultRid = updateDescRid.Default.(string)
	// updateDescCrc32 is the schema descriptor for crc32 field.
	updateDescCrc32 := updateFields[4].Descriptor()
	// update.DefaultCrc32 holds the default value on creation for the crc32 field.
	update.DefaultCrc32 = updateDescCrc32.Default.(string)
	// updateDescAttr is the schema descriptor for attr field.
	updateDescAttr := updateFields[5].Descriptor()
	// update.DefaultAttr holds the default value on creation for the attr field.
	update.DefaultAttr = updateDescAttr.Default.(string)
	// updateDescForcibly is the schema descriptor for forcibly field.
	updateDescForcibly := updateFields[6].Descriptor()
	// update.DefaultForcibly holds the default value on creation for the forcibly field.
	update.DefaultForcibly = updateDescForcibly.Default.(bool)
	// updateDescTruncate is the schema descriptor for truncate field.
	updateDescTruncate := updateFields[7].Descriptor()
	// update.DefaultTruncate holds the default value on creation for the truncate field.
	update.DefaultTruncate = updateDescTruncate.Default.(bool)
	// updateDescTitle is the schema descriptor for title field.
	updateDescTitle := updateFields[8].Descriptor()
	// update.DefaultTitle holds the default value on creation for the title field.
	update.DefaultTitle = updateDescTitle.Default.(string)
	// updateDescDetail is the schema descriptor for detail field.
	updateDescDetail := updateFields[9].Descriptor()
	// update.DefaultDetail holds the default value on creation for the detail field.
	update.DefaultDetail = updateDescDetail.Default.(string)
	// updateDescID is the schema descriptor for id field.
	updateDescID := updateMixinFields0[0].Descriptor()
	// update.DefaultID holds the default value on creation for the id field.
	update.DefaultID = updateDescID.Default.(func() uuid.UUID)
	versionFields := schema.Version{}.Fields()
	_ = versionFields
	// versionDescCurrent is the schema descriptor for Current field.
	versionDescCurrent := versionFields[0].Descriptor()
	// version.DefaultCurrent holds the default value on creation for the Current field.
	version.DefaultCurrent = versionDescCurrent.Default.(int)
	// version.CurrentValidator is a validator for the "Current" field. It is called by the builders before save.
	version.CurrentValidator = versionDescCurrent.Validators[0].(func(int) error)
	// versionDescLast is the schema descriptor for Last field.
	versionDescLast := versionFields[1].Descriptor()
	// version.DefaultLast holds the default value on creation for the Last field.
	version.DefaultLast = versionDescLast.Default.(int)
	// version.LastValidator is a validator for the "Last" field. It is called by the builders before save.
	version.LastValidator = versionDescLast.Validators[0].(func(int) error)
}
