// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package instruct

import "strconv"

type Type uint32

const (
	TypeNone     Type = 0
	TypeResource Type = 1
	TypeCorrect  Type = 2
	TypeReport   Type = 3
	TypeMax      Type = 4
)

var EnumNamesType = map[Type]string{
	TypeNone:     "None",
	TypeResource: "Resource",
	TypeCorrect:  "Correct",
	TypeReport:   "Report",
	TypeMax:      "Max",
}

var EnumValuesType = map[string]Type{
	"None":     TypeNone,
	"Resource": TypeResource,
	"Correct":  TypeCorrect,
	"Report":   TypeReport,
	"Max":      TypeMax,
}

func (v Type) String() string {
	if s, ok := EnumNamesType[v]; ok {
		return s
	}
	return "Type(" + strconv.FormatInt(int64(v), 10) + ")"
}
